### ISSUE TITLE
Error update Application Insights Billing Feature "sap-data-insights"

### ISSUE THREAD

**Issue by cjpark-sapcsa** [thzandvl/microhack-sap-data#2]
Hi Team, 

Does anyone seen this error before? 

azurerm_synapse_sql_pool.sqlpool: Creation complete after 3m25s [id=/subscriptions/072c0ea5-07de-4485-bd3f-9bd3d399c683/resourceGroups/microhack-sap-data-rg/providers/Microsoft.Synapse/workspaces/sapdatasynwsb9564226482bc118/sqlPools/sapdatasynsql]

Error: Error update Application Insights Billing Feature "sap-data-insights" (Resource Group "microhack-sap-data-rg"): insights.ComponentCurrentBillingFeaturesClient#Update: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Not Found" InnerError={"diagnosticcontext":"e008347b-7145-4c2f-b85e-e401110c9586","time":"2021-05-03T06:41:02.7346539Z"}

  on MachineLearning.tf line 5, in resource "azurerm_application_insights" "insights":
   5: resource "azurerm_application_insights" "insights" {

chan@Azure:~/microhack-sap-data/terraform$

**Comment by thzandvl** [comment]
Hey Chan, I didn't see this specific error before. Did you run `terraform init` at the start? Otherwise, can you try deploying the Terraform again from scratch and destroy your current deployment (`terraform destroy`)?

**Comment by cjpark-sapcsa** [comment]
Hi Team, 

did the destroy including the rm for folder.  Then the deployment was done correctly 

azurerm_application_insights.insights: Creation complete after 20s [id=/subscriptions/072c0ea5-07de-4485-bd3f-9bd3d399c683/resourceGroups/microhack-sap-data-rg/providers/microsoft.insights/components/sap-data-insight
